<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.hiwepy</groupId>
        <artifactId>ddd4j-boot-cmpt</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-boot-cmpt-external</artifactId>

    <dependencies>
        <!-- For SLF4J -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <!-- For Ddd4j -->
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>ddd4j-boot-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- For geodesy -->
        <dependency>
            <groupId>org.gavaghan</groupId>
            <artifactId>geodesy</artifactId>
        </dependency>
        <!-- For Ip2region -->
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>ip2region-spring-boot-starter</artifactId>
        </dependency>
        <!-- For OSI -->
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
        </dependency>
        <!-- For Redis -->
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>redistpl-plus-spring-boot-starter</artifactId>
        </dependency>
        <!-- Compile dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
    </dependencies>

</project>
