<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j.boot</groupId>
        <artifactId>ddd4j-boot-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../ddd4j-boot-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-boot-web</artifactId>
    <packaging>pom</packaging>
    <description>ddd4j Spring Boot Web 自动装配聚合。</description>

    <modules>
        <module>ddd4j-boot-web-webmvc</module>
        <module>ddd4j-boot-web-webflux</module>
        <module>ddd4j-boot-web-javalin</module>
        <module>ddd4j-boot-web-vertx</module>
    </modules>
</project>
