com.github.hiwepy.boot.autoconfigure.DefaultMessageSourceAutoConfiguration=
com.github.hiwepy.boot.autoconfigure.DefaultSequenceConfiguration=
com.github.hiwepy.boot.autoconfigure.DefaultSpringContextConfiguration=
com.github.hiwepy.boot.autoconfigure.DefaultWebFluxConfiguration=
