<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.hiwepy</groupId>
        <artifactId>ddd4j-boot-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../ddd4j-boot-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-boot-cmpt</artifactId>
    <packaging>pom</packaging>
    <description>Ddd4j Boot Components Parent Module</description>

    <modules>
        <module>ddd4j-boot-cmpt-akka</module>
        <module>ddd4j-boot-cmpt-cola</module>
        <module>ddd4j-boot-cmpt-crypto</module>
        <module>ddd4j-boot-cmpt-datascope</module>
        <module>ddd4j-boot-cmpt-external</module>
        <module>ddd4j-boot-cmpt-jackson</module>
        <module>ddd4j-boot-cmpt-kafka</module>
        <module>ddd4j-boot-cmpt-license</module>
        <module>ddd4j-boot-cmpt-logs</module>
        <module>ddd4j-boot-cmpt-pf4j</module>
        <module>ddd4j-boot-cmpt-satoken</module>
        <module>ddd4j-boot-cmpt-validation</module>
        <module>ddd4j-boot-cmpt-webflux</module>
        <module>ddd4j-boot-cmpt-webmvc</module>
    </modules>

</project>
