<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j.boot</groupId>
        <!-- 特别注意：真实的业务系统应继承 ddd4j-boot-parent -->
        <artifactId>ddd4j-boot-samples</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-boot-sample-common</artifactId>

    <dependencies>
        <!-- For DDD4j Boot -->
        <dependency>
            <groupId>io.ddd4j.boot</groupId>
            <artifactId>ddd4j-boot-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.ddd4j.boot</groupId>
            <artifactId>ddd4j-boot-web-webmvc</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- For Cola -->
        <dependency>
            <groupId>com.alibaba.cola</groupId>
            <artifactId>cola-component-dto</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cola</groupId>
            <artifactId>cola-component-exception</artifactId>
        </dependency>
    </dependencies>

</project>