<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j.boot</groupId>
        <artifactId>ddd4j-boot-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../../ddd4j-boot-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-boot-sample-cqrs-person-shared</artifactId>
    <description>Spring Boot Person CQRS 示例共享模型：复用 ddd4j 纯 Java Person CQRS 样例</description>

    <dependencies>
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-sample-cqrs-person</artifactId>
            <version>${ddd4j.version}</version>
        </dependency>
    </dependencies>
</project>
