<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.hiwepy</groupId>
        <artifactId>ddd4j-boot-cmpt</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>ddd4j-boot-cmpt-crypto</artifactId>

    <dependencies>
        <!-- For Jeebiz API -->
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>ddd4j-boot-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>ddd4j-boot-cmpt-jackson</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- For Okhttp3 -->
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>okhttp3-spring-boot-starter</artifactId>
        </dependency>
        <!-- For Spring Webmvc -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
        </dependency>
        <!-- For Crypto -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
        </dependency>

    </dependencies>

</project>
