<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j.boot</groupId>
        <artifactId>ddd4j-boot-cmpt</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-boot-cmpt-security</artifactId>
    <description>Ddd4j Boot Security Component</description>

    <dependencies>
        <!-- For DDD4j Core -->
        <dependency>
            <groupId>io.ddd4j.boot</groupId>
            <artifactId>ddd4j-boot-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- For Spring Security -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>security-biz-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>security-jwt-spring-boot-starter</artifactId>
        </dependency>
        <!-- For Redis -->
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>redistpl-plus-spring-boot-starter</artifactId>
        </dependency>
        <!-- Compile dependencies -->
        <dependency>
            <groupId>com.github.hiwepy</groupId>
            <artifactId>jwt-issuer-with-jjwt</artifactId>
        </dependency>
    </dependencies>

</project>