<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.ddd4j.boot</groupId>
        <artifactId>ddd4j-boot-tx</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ddd4j-boot-tx-local</artifactId>
    <name>ddd4j-boot-tx-local</name>
    <description>Ddd4j Boot Local Transaction Auto-Configuration</description>

    <dependencies>
        <!-- ddd4j-tx-core -->
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-tx-core</artifactId>
            <version>${ddd4j.version}</version>
        </dependency>
        <!-- Spring Boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
    </dependencies>

</project>
