io.ddd4j.web.webflux.DefaultMessageSourceAutoConfiguration=
io.ddd4j.web.webflux.DefaultSequenceConfiguration=
io.ddd4j.web.webflux.DefaultSpringContextConfiguration=
io.ddd4j.web.webflux.DefaultWebFluxConfiguration=
